version: '2'
services:
  nginx:
    build: ./docker/nginx
    restart: always
    ports:
      - '8080:80'
    volumes:
      - ./log/nginx:/var/log/nginx
  mysql:
    build: ./docker/mysql
    restart: always
    environment:
      MYSQL_DATABASE: selfphp
      MYSQL_USER: selfusr
      MYSQL_PASSWORD: selfpass
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - db:/var/lib/mysql
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d
  app:
    build: ./docker/phpfpm
    restart: always
    volumes:
      - ./log/fpm:/log/fpm
      - ./app:/var/www/html
    depends_on:
      - nginx
      - mysql
  composer:
    build: ./docker/composer
    volumes:
      - ./app:/app
volumes:
  db:
